### PR TITLE
(Quick)fixed issue with ghc-8.0.1.

### LINKED ISSUE #2: Issue when compiling with ghc-8.0.1
Due to the new conservative use of superclasses, compiling type-level with ghc-8.0.1 outputs an error.

### PR DESCRIPTION
**Pull request by ugeorge**
This fix should close #2 needed further on for #1 .

cabal-1.22 does not complain, whereas cabal-1.24 does throw some warnings about redundant constraints. One might look into it. Check [Build Status](https://travis-ci.org/ugeorge/type-level)

@HWoidt : could you please honour this pull request and (eventually) take care of the remaining warnings?

**EDIT** 

In the worst case the warnings can be suppressed by compiling with the `-Wno-redundant-constraints` flag. I do not want to do that since I am not aware of the implementation details.

### CODE REVIEW

File: src/Data/TypeLevel/Num/Ops.hs [hunk 1]
```diff
@@ -386,7 +386,7 @@ infixr 8 ^
 -- @log_base_b x = e@
 --  Note it is not relational (i.e. cannot be used to express exponentiation)
 class (Pos b, b :>=: D2, Pos x, Nat e) =>  LogBase b x e  | b x -> e 
-instance  LogBaseF b x e f => LogBase b x e
+instance  (Pos b, b :>=: D2, Pos x, Nat e, LogBaseF b x e f) => LogBase b x e
```
Comment (2opremio) [inline src/Data/TypeLevel/Num/Ops.hs:389]: It sucks that this is needed :) . What error were you getting?

Comment (ugeorge) [inline src/Data/TypeLevel/Num/Ops.hs:389]: Yeah, it seems so ([Migration/8.0](https://ghc.haskell.org/trac/ghc/wiki/Migration/8.0)). Thanks for answering so quick!

Check the output for Job #5.2 here [Build Status](https://travis-ci.org/ugeorge/type-level)

It complains heavily along the lines of:

```
src/Data/TypeLevel/Num/Ops.hs:375:10: warning: [-Wredundant-constraints]
    • Redundant constraint: ExpBase b D7 r
    • In the instance declaration for ‘ExpBase b D8 r'’
```

As I said, these warnings could just be suppressed . On the other hand I cannot estimate the effort in trying to deal with them. Would taking out these "redundant" constraints mess up (too much) the state of the library?

P.S.: no errors, just warnings...

Comment (2opremio) [inline src/Data/TypeLevel/Num/Ops.hs:389]: I've read the release notes and your fix looks fine. It's a pity that the code becaomes so verbose though, so I would favor disabling the warning instead due to our abuse of typeclasses I think it would be justified.

Comment (ugeorge) [inline src/Data/TypeLevel/Num/Ops.hs:389]: Will do, thanks!
